- type: job
  parent: CMJobBase
  id: CMStandartPMC
  name: cm-job-name-standart-pmc
  description: cm-job-description-standart-pmc
  playTimeTracker: CMJobStandartPMC
  weight: 10
  startingGear: CMGearStandartPMC
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: cm-job-supervisors-we-ya
  accessGroups:
  - ShipMasterAccess
  - Corp

- type: startingGear
  id: CMGearStandartPMC
  equipment:
    jumpsuit: RMCJumpsuitVeteranPMC
    back: CMSatchelMarinePMCStandart
    belt: CMStunbaton
    shoes: RMCBootsPMCFilled
    mask: CMMaskArmoredCoifPMC
    head: CMArmorHelmetTacticalPMC
    outerClothing: CMArmorPMC
    suitstorage: WeaponSMGM39B2
    id: CMIDCardPMC
    ears: RMCHeadsetDistressPMC
    gloves: RMCHandsVeteranPMC
    pocket1: RMCPouchMagazineLargePMC
    pocket2: RMCPouchFirstAidInjectors
  inhand:
  - CMWebbingBlackPMC

- type: job
  parent: CMJobBase
  id: CMGunnerPMC
  name: cm-job-name-gunner-pmc
  description: cm-job-description-gunner-pmc
  playTimeTracker: CMJobGunnerPMC
  weight: 10
  startingGear: CMGearGunnerPMC
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: cm-job-supervisors-we-ya
  accessGroups:
  - ShipMasterAccess
  - Corp

- type: startingGear
  id: CMGearGunnerPMC
  equipment:
    jumpsuit: RMCJumpsuitVeteranPMC
    mask: CMMaskArmoredCoifPMC
    shoes: RMCBootsPMCFilled
    head: CMArmorHelmetHeavyPMC
    outerClothing: CMArmorHeavyPMC
    suitstorage: RMCSmartGun
    belt: CMBeltSmartGunOperatorFilled
    id: CMIDCardGunnerPMC
    ears: RMCHeadsetDistressPMC
    gloves: RMCHandsVeteranPMC
    eyes: RMCGlassesSmartGunSight
    pocket1: RMCPouchFirstAidInjectors
  inhand:
  - CMWebbingBlackPMC

- type: job
  parent: CMJobBase
  id: CMMedicPMC
  name: cm-job-name-medic-pmc
  description: cm-job-description-medic-pmc
  playTimeTracker: CMJobMedicPMC
  weight: 10
  startingGear: CMGearMedicPMC
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: cm-job-supervisors-we-ya
  accessGroups:
  - ShipMasterAccess
  - Corp

- type: startingGear
  id: CMGearMedicPMC
  equipment:
    jumpsuit: RMCJumpsuitVeteranPMC
    back: CMSatchelMarinePMCMedic
    mask: CMMaskArmoredCoifPMC
    belt: CMBeltMedicBagFilled
    shoes: RMCBootsPMCFilled
    head: CMArmorHelmetTacticalPMC
    outerClothing: CMArmorPMC
    suitstorage: WeaponSMGM39B2
    id: CMIDCardMedicPMC
    ears: RMCHeadsetDistressPMC
    gloves: RMCHandsVeteranPMC
    eyes: RMCGlassesMedicalHUDGlasses
    pocket1: RMCPouchAutoinjectorFill
    pocket2: RMCPouchMagazineLargePMC
  inhand:
  - CMWebbingBlackPMC

- type: job
  parent: CMJobBase
  id: CMSniperPMC
  name: cm-job-name-sniper-pmc
  description: cm-job-description-sniper-pmc
  playTimeTracker: CMJobSniperPMC
  weight: 10
  startingGear: CMGearSniperPMC
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: cm-job-supervisors-we-ya
  accessGroups:
  - ShipMasterAccess
  - Corp

- type: startingGear
  id: CMGearSniperPMC
  equipment:
    jumpsuit: RMCJumpsuitVeteranPMC
    back: WeaponSMGM39B2
    belt: RMCBeltUtilityGeneralPMCSniper
    mask: CMMaskArmoredCoifPMC
    shoes: RMCBootsPMCFilled
    head: CMArmorHelmetSniperPMC
    outerClothing: CMArmorSniperPMC
    suitstorage: CMM42CSniperRifle
    id: CMIDCardSniperPMC
    ears: RMCHeadsetDistressPMC
    eyes: CMGlassesM42ScoutSight
    gloves: RMCHandsVeteranPMC
    pocket1: RMCPouchMagazineLargePMCSniper
    pocket2: RMCPouchFirstAidInjectors
  inhand:
  - CMWebbingBlackPMC

- type: job
  parent: CMJobBase
  id: CMOfficerPMC
  name: cm-job-name-officer-pmc
  description: cm-job-description-officer-pmc
  playTimeTracker: CMJobOfficerPMC
  weight: 10
  startingGear: CMGearOfficerPMC
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: cm-job-supervisors-we-ya
  accessGroups:
  - ShipMasterAccess
  - Corp

- type: startingGear
  id: CMGearOfficerPMC
  equipment:
    jumpsuit: RMCJumpsuitVeteranPMCLeader
    back: CMSatchelMarine
    belt: CMStunbaton
    mask: CMMaskArmoredLeaderCoifPMC
    shoes: RMCBootsPMCFilled
    head: CMArmorHelmetBeretPMC
    outerClothing: CMArmorOfficerPMC
    suitstorage: WeaponRifleM54A2
    id: CMIDCardOfficerPMC
    ears: RMCHeadsetDistressPMC
    gloves: RMCHandsVeteranPMC
    eyes: RMCGlassesMedicalHUDGlasses
    pocket1: RMCPouchMagazineLargePMCLeader
    pocket2: RMCPouchAutoinjectorFill
  inhand:
  - CMWebbingBlackPMC
  storage:
    back:
    - CMCrowbar
    - CMGrenadeFragOld 
    - RMCExplosiveBreachingCharge
    - RMCRangefinder
    - CMMagazineRifleM54CAP
    - CMMagazineRifleM54CAP

- type: playTimeTracker
  id: CMJobStandartPMC

- type: playTimeTracker
  id: CMJobGunnerPMC

- type: playTimeTracker
  id: CMJobMedicPMC

- type: playTimeTracker
  id: CMJobSniperPMC

- type: playTimeTracker
  id: CMJobOfficerPMC
