# Предустановка конфигурации, используемая на сервере Stories Colonial Marines Flux.
# Загружается перед настройками конфигурации, специфичными для сервера.

# [config]
# presets = "Stories/flux"

[adminlogs]
server_name = "Space Stories - Colonial Marines Flux 🌑"

[game]
hostname = "📚 Space Stories - Colonial Marines Flux 🌑 [TTS]"
desc = """
                                                            📕 𝗦𝗽𝗮𝗰𝗲 𝗦𝘁𝗼𝗿𝗶𝗲𝘀 - Colonial Marines! 🌍
•────────────────────────────────── ✧ ──────────────────────────────────•
  🌠 ⋮ Сервер со средним уровнем требований к ролевому отыгрышу.
  ⚙ ⋮ Сборка сервера основана на https://github.com/RMC-14/RMC-14.
•────────────────────────────────── ✧ ──────────────────────────────────•
                                            📚 Присоединяйтесь к нашему дружному сообществу 📚"""
maxplayers = 200
soft_max_players = 100

[hub]
server_url = "ss14s://spacestories.club/flux"
